### ISSUE TITLE
The installed version of package kernel is not compatible, require 6.6.54~180e8a62…-r1 while 6.6.52~f081eedc…-r1 is installed.

### ISSUE THREAD

**Issue by mick-pihole** [arix00/openwrt-mx4300#16]
### Describe the bug

trying to install wireguard., got this error

### OpenWrt version

r0-e93685c

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

install wireguard-tools

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
read document, it's in release note.

**Comment by mick-pihole** [comment]
> read document, it's in release note.

thanks. got it installed with hack.
