### ISSUE TITLE
 openvpn-openssl Install - dependency kernal 6.6.56

### ISSUE THREAD

**Issue by ragiovan** [arix00/openwrt-mx4300#18]
### Describe the bug

Error when trying to install openvpn-openssl software package:

Installing openvpn-openssl (2.6.12-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/openvpn-openssl_2.6.12-r1_aarch64_cortex-a53.ipk
Installing libcap-ng (0.8.4-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/libcap-ng_0.8.4-r1_aarch64_cortex-a53.ipk
Installing liblzo2 (2.10-r4) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/liblzo2_2.10-r4_aarch64_cortex-a53.ipk
Installing liblz4-1 (1.10.0-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/liblz4-1_1.10.0-r1_aarch64_cortex-a53.ipk
Installing libopenssl3 (3.0.15-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/libopenssl3_3.0.15-r1_aarch64_cortex-a53.ipk
Configuring libopenssl3.
Configuring liblzo2.
Configuring libcap-ng.
Configuring liblz4-1.
Configuring openvpn-openssl.
Errors
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.56~5b0677ecb7d8a222953dfec8731c28f4-r1) for kmod-tun
 * 
### OpenWrt version

 r0-be05e54

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

Go to Software section, and try to install latest openvpn-openssl

### Actual behaviour

The above error message

### Expected behaviour

install

### Additional info

Tried to update kernal with

opkg install kernel
Package kernel (6.6.54~51842a4b08c6aa87920627d8ef34b510-r1) installed in root is up to date.

It looks like it needs a higher kernal version. Don't know if this is something easy to do?

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
read document.
