### ISSUE TITLE
when install zerotier shows kernel ver wrong, currenct is 6.6.54, need 6.6.56

### ISSUE THREAD

**Issue by zc3721** [arix00/openwrt-mx4300#19]
### Describe the bug

when install zerotier shows kernel ver wrong, currenct is 6.6.54, need 6.6.56

### OpenWrt version

r0-7a93ddc

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

 Linksys MX4300

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
read document its in release note.
