### ISSUE TITLE
mx4300 third wireless interface does not work

### ISSUE THREAD

**Issue by cgigate** [arix00/openwrt-mx4300#21]
### Describe the bug

mx4300 has 1 2.4Ghz and 2x 5G wireless interfaces. The second 5G wireless interface is not working; it labels as a 6Ghz interface (Qualcomm Atheros IPQ8074 802.11ac/ax/n) from the build; actually, it is not a 6Ghz interface; it should be 5Ghz. and it does not work at all. Some workaround can make it work temporarily, that is, change the preset channel to "auto,"  then it works, but after reboot, it stops working again.

### OpenWrt version

r0-48eaa44

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

it is obvious to see from scratch, the third wireless interface shows on status as "disabled", even it already enable from "network>wireless".
or you can disable other two wireless interfaces, to play the third interface only

### Actual behaviour

no wifi

### Expected behaviour

there should be 5Ghz wifi

### Additional info

![image_2024-10-14_174507231](https://github.com/user-attachments/assets/f6dc4a7d-4161-4a1c-80ee-d232e9f926ae)

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by cgigate** [comment]
![image_2024-10-14_174832983](https://github.com/user-attachments/assets/ed5cb460-6a38-47da-98e3-0122f5426bf4)

**Comment by arix00** [comment]
Very likely your device doesn't support channel 177.
If 'auto' always picks 177 set it to some fixed lower channel like 149.

A disabled radio looks quite different and mostly happens when you select a DFS channel.

A screenshot of 'disabled' radio with DFS CH-100. 

![Snap1](https://github.com/user-attachments/assets/b7afa215-db3e-4f85-aade-8a52fd8396ab)

**Comment by cgigate** [comment]
Thanks arix00, 
I have three MX4300s (LN1301) purchased separately from Amazon/woot month apart..
All have exactly the same problem,  the wireless interface 3 (Qualcomm Atheros IPQ8074 802.11ac/ax/n) does not work with build,  booted to (partition 2) back to original stock firmware, all three wireless interfaces are perfectly fine.
Here is another screen capture for a fresh full reset, I only clicked to enabled interface 3 , it shows "Channel: 100 (6.450 GHz)", obviously it is wrong, and not working.
![image_2024-10-14_210153922](https://github.com/user-attachments/assets/c32db807-f1fa-43bf-adb8-bb389cb80859)
Another screen from "Status"
![image_2024-10-14_210348944](https://github.com/user-attachments/assets/d2085ead-2a34-4281-9b64-704a4da9504c)

**Comment by gittyaf** [comment]
These radio settings aren't setup to list the valid frequencies they can support I think. radio0 is limited to channel 36-44, and radio2 is limited to 144-165 I believe. I set the channels manually so the invalid ones don't get autopicked and everything's fine. Had to reboot a few times though.

**Comment by cgigate** [comment]
reboot does not fix the problem...
the issue is persistence in the new release

**Comment by weilinear** [comment]
I am having exactly the same issues. Third wifi wifi shows as 6ghz and cannot be enabled.
