### ISSUE TITLE
`qualcommax-nss-3138184` dont have `nss_packages` and `sqm_scripts` in its default freeds

### ISSUE THREAD

**Issue by AlexCai26** [arix00/openwrt-mx4300#22]
### Describe the bug

it seems in the release tag of `[qualcommax-nss-3138184](https://github.com/arix00/openwrt-mx4300/releases/tag/qualcommax-nss-3138184)`, The feeds `nss_packages` and `sqm_scripts` are missing from its `feeds.conf.default`.

### OpenWrt version

SNAPSHOOT

### OpenWrt release

qualcommax-nss-3138184

### OpenWrt target/subtarget

MX4300

### Device

MX4300

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
I'm not using nss myself so may be wrong, these 2 are built from qosmio's github, obviously no way to publish them directly...I mean, do you expect some url to be added for them to opkg? the `sqm_scripts_nss` can be installed manually and is nss-firmware package really necessary?

```
 $ ls nss_packages/
index.json
nss-firmware-default_2024.08.04~794fe373-r1_aarch64_cortex-a53.ipk
nss-firmware-ipq8074_2024.08.04~794fe373-r1_aarch64_cortex-a53.ipk
Packages
Packages.gz
Packages.manifest
Packages.sig
tmp
$ ls sqm_scripts_nss/
index.json  Packages.gz        Packages.sig                         tmp
Packages    Packages.manifest  sqm-scripts-nss_20240510-r1_all.ipk
```
