### ISSUE TITLE
opkg update failed with following messages

### ISSUE THREAD

**Issue by us-sprint1** [arix00/openwrt-mx4300#26]
### Describe the bug

Collected errors:
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz, wget returned 8.

Check the network status and the router is connected with internet. Can ping to downloads.openwrt.org too.

Thanks,
Peter

### OpenWrt version

qualcommax-nss-7a9d4c3 

### OpenWrt release

qualcommax-nss-7a9d4c3 

### OpenWrt target/subtarget

qualcommax-nss-7a9d4c3 

### Device

ln1301 or mx4300

### Image kind

Official downloaded image

### Steps to reproduce

type opkg update in command line

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by us-sprint1** [comment]
"opkg update" worked ok several days ago

**Comment by arix00** [comment]
openwrt now moves to apk as default package management, and upstream snapshot feed updated to be apk-compatible only. 

but 24.10 rc will still on opkg and unsure about 24.10 release. So we might see both for a while.

currently lots of issues/fixes around apk, please wait few days I'll make a new apk build.

**Comment by us-sprint1** [comment]
Thanks for your quick response.

**Comment by famewolf** [comment]
I just installed the build on my LN1301 and was glad to see this posted.  Was worried I'd messed up the install somehow.

**Comment by Torbins** [comment]
For now you can manually download some packages from https://downloads.openwrt.org/releases/23.05.5/targets/ipq807x/generic/packages/ and also replace each "https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53" with "https://downloads.openwrt.org/releases/packages-24.10/aarch64_cortex-a53" in opkg settings. This should allow you to install almost anything. But I really hope that they will branch 24.10.0-rc1 soon.

**Comment by famewolf** [comment]
On the snapshot released roughly 15 hours ago, radio2 shows as disabled even though I've enabled it.

**Comment by arix00** [comment]
Most likely it's on DFS channel. Set country to US. If it's still not working just use a regular channel(149-161).

**Comment by famewolf** [comment]
Thank you arix00!
