### ISSUE TITLE
Wifi Issue With qualcommax-nss-snapshot-6e7e433

### ISSUE THREAD

**Issue by DonutMango** [arix00/openwrt-mx4300#28]
### Describe the bug

Experiencing wifi issues with FOSS build and seeing errors below via logread:
```
Tue Nov 19 20:54:13 2024 kern.warn kernel: [   88.883932] ath11k c000000.wifi: failed to flush transmit queue, data pkts pending 1
Tue Nov 19 20:54:23 2024 kern.warn kernel: [   99.284045] ath11k c000000.wifi: failed to flush transmit queue, data pkts pending 3
Tue Nov 19 20:54:28 2024 kern.warn kernel: [  104.564149] ath11k c000000.wifi: failed to flush transmit queue, data pkts pending 7
```

### OpenWrt version

r0-c469d48

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys LN1301/MX4300

### Image kind

Official downloaded image

### Steps to reproduce

```
scp openwrt-qualcommax-ipq807x-linksys_mx4300-squashfs-factory.bin 192.168.1.1:/tmp/factory.bin
mtd -r -e kernel -n write /tmp/factory.bin kernel
```

### Actual behaviour

Unstable 5ghz wifi.

### Expected behaviour

Stable 5ghz wifi.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
Known issue on upstream.

https://github.com/openwrt/openwrt/issues/14965
