### ISSUE TITLE
kmod wireguard is missing from repositories

### ISSUE THREAD

**Issue by camtanni** [arix00/openwrt-mx4300#40]
### Describe the bug

Trying to add wireguard-tools, luci-app-wireguard, and get an error that "Required dependency package kmod-wireguard is not available in any repository." I followed the docs provided on the "use kmods", added the @main and copied all the repositories to my distfeeds.list file. 

I'm also getting an error saying "WARNING: updating and opening https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/packages.adb   : remote server returned error (try 'apk update')" when running apk update, so I don't know if the issues are tied or not, although I wasn't able to install wireguard apps, so followed the "use kmods" steps and now have the "WARNING" issue. 
Any help on either issues would be greatly appreciated. Thanks.

### OpenWrt version

r28141-52519a59a8

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

See "Describe the Bug"

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
Thanks for reporting!

sth changed on upstream(for good) and as a result, kmod info is missing I'll fix it.

https://github.com/openwrt/openwrt/issues/17036

**Comment by arix00** [comment]
new build is up.
and no longer need '@main' tag as kmods are now removed from upstream package feed.

**Comment by camtanni** [comment]
New build fixed my issues, thank you!
