### ISSUE TITLE
sqm-scripts-nss-20240510-r1

### ISSUE THREAD

**Issue by famewolf** [arix00/openwrt-mx4300#42]
### Describe the bug

After installing the latest updates doing almost anything with apk (except update) results in this error:

root@OpenWrt:~# apk fix
ERROR: unable to select packages:
sqm-scripts-nss-20240510-r1:
error: uninstallable
arch: all
satisfies: world[sqm-scripts-nss]

### OpenWrt version

OpenWrt SNAPSHOT r0-6e7e433 / LuCI Master 24.328.43591~9e70c9a

### OpenWrt release

OpenWrt SNAPSHOT r0-6e7e433 / LuCI Master 24.328.43591~9e70c9a

### OpenWrt target/subtarget

OpenWrt SNAPSHOT r0-6e7e433 / LuCI Master 24.328.43591~9e70c9a

### Device

Linksys LN1301

### Image kind

Official downloaded image

### Steps to reproduce

Do an apk update then an upgrade then try to install any package.

### Actual behaviour

root@OpenWrt:~# apk fix
ERROR: unable to select packages:
sqm-scripts-nss-20240510-r1:
error: uninstallable
arch: all
satisfies: world[sqm-scripts-nss]

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
I'm on foss so can't help much.
but apk went through lots of changes/fixes recently, try update to latest release.

**Comment by famewolf** [comment]
At the time I was on the latest release.  I reverted to a previous backup and just have not upgraded to the latest luci update.
