### ISSUE TITLE
kmod tar file missing kmod-vxlan

### ISSUE THREAD

**Issue by moh1t** [arix00/openwrt-mx4300#43]
### Describe the bug

the kmod archive that comes with NSS build is missing kmod-vxlan. The one from openwrt is not installing as the kernel version is different. Can you please include kmod-vxlan as well for the latest release?

### OpenWrt version

qualcommax-nss-snapshot-r28146-52b6c92479

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

MX4300

### Image kind

Official downloaded image

### Actual behaviour

The kmod.tar.gz file is missing kmod-vxlan package

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
When set vxlan as module, kmod-qca-nss-ecm also becomes a module instead of builtin.
so vxlan must be either builtin or leftout.
same for nat46.

I'll see if there is any work around or may be just built them in?

**Comment by arix00** [comment]
new release. it's builtin now.

**Comment by moh1t** [comment]
Thank you, working great
