### ISSUE TITLE
include block-mount package

### ISSUE THREAD

**Issue by ohnggni** [arix00/openwrt-mx4300#44]
Firstly, thank you for building and providing great images.
Just one thing I would like you to is...
Can you kindly include 'block-mount package' in your build image?
In fact, I maintain many of back up files, configurations in my usb stick, which is constantly attached to the mx4300's port.
I'd like to use them more conveniently right after installing your future NSS snapshots without manually adding block-mount apk.

Please consider that positively.

Thanks!

**Comment by arix00** [comment]
`mount /dev/sda1 /mnt`
