### ISSUE TITLE
Reboot logs you out but does not reboot.

### ISSUE THREAD

**Issue by famewolf** [arix00/openwrt-mx4300#48]
### Describe the bug

Picking reboot from the menu or via the luci-app-advancedreboot will log you out but doesn't actually reboot the router.

### OpenWrt version

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### OpenWrt release

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### OpenWrt target/subtarget

OpenWrt SNAPSHOT r28217-af611bce44 / LuCI Master 24.335.53348~98c0413

### Device

LN1301

### Image kind

Official downloaded image

### Steps to reproduce

Try to reboot.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
I'm on an older  r28199-1bdb6d8404 and no problem here. does `reboot` from ssh work?
or you can try some other build.

**Comment by famewolf** [comment]
Does not appear to work from ssh either.

***@***.***:/mnt/sda1/root# reboot
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root#
***@***.***:/mnt/sda1/root# ls

**Comment by famewolf** [comment]
Installed most recent foss snapshot and also doesn't reboot but will assume it's a snapshot issue.

**Comment by arix00** [comment]
I also installed lastest foss  r28339-8a7239009c and no problem with reboot. 

You may try to reflash, without saving old config, and then reboot after initial boot.  If reboot not working, anything unusual in `dmesg` and `logread`?

**Comment by famewolf** [comment]
I'm wondering now if one of the jobs from crontab or at startup is preventing it..for example I have 3 cloud storage providers mounted via rclone...and several other tasks.  I see it issuing the shutdown.

<**Wed Dec 18 18:09:05 2024 daemon.info procd: - shutdown -**
Wed Dec 18 18:09:10 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:09:20 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:09:21 2024 daemon.err uhttpd[29078]: [info] luci: accepted login on / for root from 192.168.3.92
Wed Dec 18 18:09:30 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:09:40 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:09:50 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:00 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:00 2024 cron.err crond[2444]: file root:
Wed Dec 18 18:10:00 2024 cron.err crond[2444]:  line find "/root" -type f -name "backup-*.tar.gz" | sort -r | awk 'NR > 100' | xargs rm -f; sysupgrade -b "/mnt/sda1/backups/backup-${HOSTNAME}-$(date +\%Y-\%m-\%d-\%H-\%M-\%S).tar.gz"
Wed Dec 18 18:10:00 2024 cron.err crond[2444]:  line rm /mnt/sda1/tmp/tmo-mon.log
Wed Dec 18 18:10:00 2024 cron.err crond[2444]:  line tmo-monitor.py --skip-bands --skip-5g-bands --ping-count 3 admin f1 >> /mnt/sda1/tmp/tmo-mon.log
Wed Dec 18 18:10:00 2024 cron.err crond[2444]:  job: 0 tmo-monitor.py --skip-bands --skip-5g-bands --ping-count 3 admin f1 >> /mnt/sda1/tmp/tmo-mon.log
Wed Dec 18 18:10:00 2024 cron.err crond[2444]: file root:
Wed Dec 18 18:10:00 2024 cron.err crond[24348]: child running /bin/ash
Wed Dec 18 18:10:00 2024 cron.err crond[2444]: USER root pid 24348 cmd tmo-monitor.py --skip-bands --skip-5g-bands --ping-count 3 admin f1 >> /mnt/sda1/tmp/tmo-mon.log
Wed Dec 18 18:10:01 2024 daemon.notice hostapd: phy1-ap0: STA e4:be:ed:09:67:1f IEEE 802.11: did not acknowledge authentication response
Wed Dec 18 18:10:10 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:20 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:30 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:40 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:10:50 2024 cron.err crond[2444]: wakeup dt=10
Wed Dec 18 18:11:00 2024 cron.err crond[2444]: user:root entry:(null)
Wed Dec 18 18:11:00 2024 cron.err crond[2444]: user:root entry:(null)
Wed Dec 18 18:11:00 2024 cron.err crond[2444]: user:root entry:(null)
Wed Dec 18 18:11:00 2024 cron.err crond[2444]: wakeup dt=10
>

For now I can put up with not rebooting.  Appreciate you taking the time to check.

**Comment by arix00** [comment]
fwiw, `cron.err crond` are not error just how busybox works in openwrt.  

https://dev.archive.openwrt.org/ticket/3981

however if reboot works in a clean system you need to check your installed packages.
