### ISSUE TITLE
kmod

### ISSUE THREAD

**Issue by smashrvmco** [arix00/openwrt-mx4300#50]
### Describe the bug

Trying to add a usb printer, I have installed packages p910nd and luci-app-p910nd, but it also needs either kmod-lp or kmod-usb-printer in order to work, neither of which are available in the software lists. If you could add one or both of these (it says it is safe to have both installed) it would be much appreciated
thanks

### OpenWrt version

r28280-ff5f77ecdd

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
they're readily available in foss.
for nss build, you need to sideload the kmods. see release document.
