### ISSUE TITLE
kmod-nf-conntrack-netlink

### ISSUE THREAD

**Issue by AirLHY** [arix00/openwrt-mx4300#51]
### Describe the bug

Unable to install "dnsmasq-full" while attempting to use packages relying on "iptables" and "ipset", as "dnsmasq-full" requires the dependency "kmod-nf-conntrack-netlink". Any help installing "dnsmasq-full" or integrating it into future builds (to replace the feature-limited "dnsmasq") would be much appreciated. Thank you for the hard work!

### OpenWrt version

r28211-d55754ce0d

### OpenWrt release

24.10.0-rc4

### OpenWrt target/subtarget

qualcommax/ipq807x

### Device

Linksys MX4300

### Image kind

Official downloaded image

### Steps to reproduce

root@OpenWrt:~# opkg install dnsmasq-full
Installing dnsmasq-full (2.90-r3) to root...
Downloading https://downloads.openwrt.org/releases/24.10.0-rc4/packages/aarch64_cortex-a53/base/dnsmasq-full_2.90-r3_aarch64_cortex-a53.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nf-conntrack-netlink for libnetfilter-conntrack3
 * pkg_hash_fetch_best_installation_candidate: Packages for libnetfilter-conntrack3 found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for dnsmasq-full:
 *      kmod-nf-conntrack-netlink
 * opkg_install_cmd: Cannot install package dnsmasq-full.

root@OpenWrt:~# opkg install ipset
Unknown package 'ipset'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-ipset for libipset13
 * pkg_hash_fetch_best_installation_candidate: Packages for libipset13 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-ipset for ipset
 * pkg_hash_fetch_best_installation_candidate: Packages for ipset found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ipset.
 
 

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by arix00** [comment]
read the document
